version: "3.3"
services:

  cache:
    image: "redis:alpine"
    command: redis-server --port 6360
    ports:
      - "6379:6360"
    expose:
      - "6379"
    environment:
      - MODE=PROD

  alert_generator:
    build:
      context: .
      dockerfile: ./alert_generator/Dockerfile
    depends_on:
      - cache
    environment:
      - MODE=PROD

  alert_runner:
    build: .
    command: python3 -u alert_runner_init.py
    environment:
      - MODE=PROD
    depends_on:
      - cache

  updater:
    build: .
    command: python3 history_updater.py
    environment:
      - MODE=PROD
    depends_on:
      - cache
#Todo: why should web service depend on generate_alert_queue?
  web:
    build: .
    command: python3 -u web_init.py
    ports:
    - "5001:5001"
    environment:
      - MODE=PROD
    depends_on:
      - cache
    volumes:
      - C:\Users\Arvid\Documents\GitHub\CryptoTracker\:/app