version: "3.3"
services:

 updater:
    build: .
    command: python3 history_updater.py
    environment:
      - REDIS_HOST=cache
    depends_on:
      - cache

 cache:
    image: "redis:alpine"
    command: redis-server --port 6360
    ports:
     - "6379:6360"
    expose:
      - "6379"

 alert_runner:
   build: .
   command: python3 alerts/alert_runner.py
   depends_on:
     - generate_alert_queue

 generate_alert_queue:
   image: "redis:alpine"
   command: redis-server --port 6361
   ports:
     - "6379:6361"
   depends_on:
     - alert_runner

 web:
    build: .
    command: python3 web_init.py
    ports:
    - "5000:5000"
    environment:
      - REDIS_HOST=cache
    depends_on:
      - cache