version: "3.3"
services:

  cache:
    image: "redis:alpine"
    command: redis-server --port 6360
    ports:
      - "6379:6360"
    expose:
      - "6379"
    environment:
      - MODE=PROD

  alert_generator:
    build:
      context: .
      dockerfile: ./alert_generator/Dockerfile
    depends_on:
      - cache
    environment:
      - MODE=PROD

  alert_runner:
    build: .
    command: python3 -u alert_runner_init.py
    environment:
      - MODE=PROD
    depends_on:
      - cache
      - alert_generator

  realtime_websocket:
    build: .
    command: python3 -u realtime_service_runner.py -s websocket
    environment:
      - MODE=PROD
    depends_on:
      - cache

  apiupdater:
    build: .
    command: python3 -u realtime_service_runner.py -s apiupdater
    environment:
      - MODE=PROD
    depends_on:
      - cache

  coin_updater:
    build: .
    command: python3 -u realtime_service_runner.py -s updater
    environment:
      - MODE=PROD
    depends_on:
      - cache
      - realtime_websocket
      - apiupdater


#Todo: why should web service depend on generate_alert_queue?
  web:
    build: .
    command: python3 -u web_init.py
    ports:
    - "5001:5001"
    environment:
      - MODE=PROD
    depends_on:
      - cache
    # volumes:
    #   - C:\Users\Arvid\Documents\GitHub\CryptoTracker\:/app
  nextjs:
    ports:
      - 3000:3000
    build:
      context: frontend/cryptotracker
      dockerfile: Dockerfile
#    volumes:
#      - ./packages/landingpage:/usr/src/app
#      - /usr/src/app/node_modules
#      - /usr/src/app/.next
    env_file:
      - .env